version: '3.8'

services:
  usecases:
    image: ghcr.io/arkiv-network/usecases-portfolio:latest
    container_name: usecases
    restart: unless-stopped
    networks:
      - arkiv_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usecases.rule=Host(`usecases.arkiv.network`)"
      - "traefik.http.routers.usecases.entrypoints=websecure"
      - "traefik.http.routers.usecases.tls.certresolver=letsencrypt"
      - "traefik.http.services.usecases.loadbalancer.server.port=80"

networks:
  arkiv_network:
    external: true